name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  frontend-unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /front
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: Install frontend modules
      run: npm run install
    - name: Run type-check
      run: npm run type-check
    - name: Run frontend unit tests 
      run: npm run test:unit

  backend-unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /back
    steps:
      - uses: actions/checkout@v4
      - name: Stable rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test